"use client";

import { useEffect, useState } from "react";
import { useCartStore } from "../../store/cartStore";
import { formatINR } from "../../lib/currency";
import Link from "next/link";

export default function CheckoutPage() {
  const items = useCartStore((state) => state.items); const clearCart = useCartStore((state) => state.clearCart); const [submitted, setSubmitted] = useState(false); const [error, setError] = useState(""); const [loadingProfile, setLoadingProfile] = useState(true); const [paymentMethod, setPaymentMethod] = useState("COD"); const [customer, setCustomer] = useState({ name: "", email: "", address: "", city: "", postalCode: "", state: "", country: "India" });
  useEffect(() => { fetch("/api/auth/session").then(async (response) => ({ response, data: await response.json() })).then(async ({ data: session }) => { if (session?.user?.role !== "CUSTOMER") throw new Error("Please log in as a customer before placing an order."); const response = await fetch("/api/customer/profile"); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load your customer details."); setCustomer((current) => ({ ...current, ...Object.fromEntries(Object.entries(data).map(([key, value]) => [key, value ?? ""])), email: session.user.email })); }).catch((loadError) => setError(loadError.message || "Unable to load your customer details.")).finally(() => setLoadingProfile(false)); }, []);
  const total = items.reduce((sum, item) => sum + Number(item.price) * item.quantity, 0);
  async function placeOrder(event) { event.preventDefault(); setError(""); try { const form = new FormData(event.currentTarget); const response = await fetch("/api/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), email: customer.email, address: form.get("address"), city: form.get("city"), postalCode: form.get("postalCode"), state: form.get("state"), country: form.get("country"), paymentMethod, items: items.map((item) => ({ id: item.id, quantity: item.quantity, selectedSize: item.selectedSize || null })) }) }); const data = await response.json(); if (!response.ok) { setError(data.error || "Unable to place order"); return; } clearCart(); setSubmitted(true); } catch { setError("Unable to connect to the store. Please try again."); } }
  if (submitted) return <section className="checkout-page section-pad"><p className="eyebrow">Order received</p><h1>Thank you<br /><em>for choosing well.</em></h1><p>Your order is being prepared. We&apos;ll send confirmation details to your inbox shortly.</p></section>;
  return <section className="checkout-page section-pad"><p className="eyebrow">Almost yours</p><h1>Complete<br /><em>your order.</em></h1><div className="checkout-layout"><form className="checkout-form" onSubmit={placeOrder}><p className="login-note">Your order will be saved to your signed-in customer account.</p><label>Full name<input name="name" onChange={(event) => setCustomer({ ...customer, name: event.target.value })} required value={customer.name} placeholder="Your name" /></label><label>Gmail / email address<input autoComplete="email" name="email" readOnly required type="email" value={customer.email} placeholder="you@gmail.com" /></label><label>Shipping address<textarea name="address" onChange={(event) => setCustomer({ ...customer, address: event.target.value })} required value={customer.address} placeholder="Street and building" /></label><div className="form-row"><label>City<input name="city" onChange={(event) => setCustomer({ ...customer, city: event.target.value })} required value={customer.city} placeholder="City" /></label><label>PIN code<input inputMode="numeric" name="postalCode" onChange={(event) => setCustomer({ ...customer, postalCode: event.target.value })} pattern="\d{4,10}" required value={customer.postalCode} placeholder="PIN code" /></label></div><div className="form-row"><label>State<input name="state" onChange={(event) => setCustomer({ ...customer, state: event.target.value })} value={customer.state} placeholder="State" /></label><label>Country<input name="country" onChange={(event) => setCustomer({ ...customer, country: event.target.value })} value={customer.country} /></label></div><fieldset className="payment-options"><legend>Payment method</legend><label><input checked={paymentMethod === "COD"} name="paymentMethod" onChange={() => setPaymentMethod("COD")} type="radio" value="COD" /> Cash on delivery</label><label><input checked={paymentMethod === "ONLINE"} name="paymentMethod" onChange={() => setPaymentMethod("ONLINE")} type="radio" value="ONLINE" /> Pay online</label>{paymentMethod === "ONLINE" && <p className="login-note">Online payment selected. Payment confirmation will be required before dispatch.</p>}</fieldset>{error && <p className="login-error">{error}</p>}<button className="button button-dark full-width" disabled={!items.length || loadingProfile || !customer.email} type="submit">{loadingProfile ? "Loading your details…" : "Place order"} <span>↗</span></button><Link className="back-link" href="/login">Log in as customer</Link></form><div className="order-summary"><h2>Your order</h2>{items.length ? items.map((item) => <div className="summary-line" key={`${item.id}-${item.selectedSize || "default"}`}><span>{item.name}{item.selectedSize ? ` · Size ${item.selectedSize}` : ""} × {item.quantity}</span><span>{formatINR(Number(item.price) * item.quantity)}</span></div>) : <p>Your bag is empty.</p>}<div className="summary-line"><strong>Total</strong><strong>{formatINR(total)}</strong></div></div></div></section>;
}
